name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: terraform
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: set credentials
      run: |
       echo "AWS_ACCESS_KEY_ID=***" >> $GITHUB_ENV
       echo "AWS_SECRET_ACCESS_KEY=***" >> $GITHUB_ENV
       echo "AWS_DEFAULT_REGION=us-west-2" >> $GITHUB_ENV
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0
    
    - name: Terraform Initialization
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan
    
    - name: Terraform Apply
      id: apply
      run: terraform apply --auto-approve
      
    
     
      
