name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: terraform
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2' # Specify the region you are working in

    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0
    
    - name: Terraform Initialization
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan
    
    - name: Terraform Apply
      id: apply
      run: terraform apply --auto-approve
      
    
     
      
