name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0
    
    - name: Terraform Initialization
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan
    
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster ${terraform output -raw ecs_cluster_id} --service ${terraform output -raw ecs_service_name} --force-new-deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2' # Specify the region you are working in
